- id: doi:10.1534/g3.117.040550
  image: https://acsess.onlinelibrary.wiley.com/cms/asset/1b72a9c4-f075-4290-a68c-cf4d7aa187d6/tpg2plantgenome2012050005-fig-0003-m.jpg
  tags:
    - breeding techniques
    - genomewide prediction