- id: doi:10.1534/g3.117.040550
  image: images/publications/neyhart2017.png
  tags:
    - breeding methods
    - genomewide prediction

- id: doi:10.3198/jpr2018.06.0037crmp
  images: images/publications/neyhart2019a.png
  tags:
    - germplasm
